### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Miosame** [goncy/styncy#1]
Hi there, thanks for this amazing theme! it's been my daily driver for the longest time - especially the monokai-subtheme.

I'm filing this issue to ask where you got the monokai hex colors from (is the origin open licensed?) and if you would be able to add a license to this repo if you did it yourself? or is it on purpose copyright reserved with no open source license.

There's plenty of themes that could benefit from this amazing sub-theme, but aren't allowed to due to missing repo license and origin source where those colors came from.

Thanks a lot in advance!

**Comment by goncy** [comment]
Hey! Glad to hear that. I think i used one dark colors for it or monokai pro (and then tweaked them) be free to do whatever you want with this, thanks for asking!

**Comment by Miosame** [comment]
@goncy awesome, thanks! though could you please [add a license](https://stackoverflow.com/a/31666878/11821602) to this repo? because until then it is copyright reserved and does not allow to be used elsewhere. 😄

**Comment by goncy** [comment]
@Miosame #2

**Comment by Miosame** [comment]
@goncy Thanks so much again!
